export const forgottenRealms = [
  {
    deities: [
      {
        deityName: "Auril, goddess of winter",
        deityAlignment: "NE",
        deityDomain: "Nature, Tempest",
        deitySymbol: "Six-pointed snowflake",
      },
      {
        deityName: "Azuth, god of wizards",
        deityAlignment: "LN",
        deityDomain: "Knowledge",
        deitySymbol: "Left hand pointing upward, outlined in fire",
      },
      {
        deityName: "Bane, god of tyranny",
        deityAlignment: "LE",
        deityDomain: "War",
        deitySymbol: "Upright black right hand, thumb and fingers together",
      },
      {
        deityName: "Beshaba, goddess of misfortune",
        deityAlignment: "CE",
        deityDomain: "Trickery",
        deitySymbol: "Black antlers",
      },
      {
        deityName: "Bhaal, god of murder",
        deityAlignment: "NE",
        deityDomain: "Death",
        deitySymbol: "Skull surronded by a ring of blood droplets",
      },
      {
        deityName: "Chauntea, goddess of agriculture",
        deityAlignment: "NG",
        deityDomain: "Life",
        deitySymbol: "Sheaf of grain or a blooming rose over grain",
      },
      {
        deityName: "Cyric, god of lies",
        deityAlignment: "CE",
        deityDomain: "Trickery",
        deitySymbol: "White jawless skull on black or purple sunburst",
      },
      {
        deityName: "Deneir, god of writing",
        deityAlignment: "NG",
        deityDomain: "Knowledge",
        deitySymbol: "Lit candle above an open eye",
      },
      {
        deityName: "Eldath, goddess of peace",
        deityAlignment: "NG",
        deityDomain: "Life, Nature",
        deitySymbol: "Waterfall plunging into still pool",
      },
      {
        deityName: "Gond, god of craft",
        deityAlignment: "N",
        deityDomain: "Knowledge",
        deitySymbol: "Toothed cog with four spokes",
      },
      {
        deityName: "Helm, god of protection",
        deityAlignment: "LN",
        deityDomain: "Life, Light",
        deitySymbol: "Staring eye on upright left gauntlet",
      },
      {
        deityName: "Ilmater, god of endurance",
        deityAlignment: "LG",
        deityDomain: "Life",
        deitySymbol: "Hands bound at the wrist with red cord",
      },
      {
        deityName: "Kelemvor, god of the dead",
        deityAlignment: "LN",
        deityDomain: "Death",
        deitySymbol: "Upright skeletal arm holding balanced scales",
      },
      {
        deityName: "Lathander, god of birth and renewal",
        deityAlignment: "NG",
        deityDomain: "Life, Light",
        deitySymbol: "Road traveling into a sunrise",
      },
      {
        deityName: "Leira, goddess of illusion",
        deityAlignment: "CN",
        deityDomain: "Trickery",
        deitySymbol: "Point-down triangle containing a swirl of mist",
      },
      {
        deityName: "Lliira, goddess of joy",
        deityAlignment: "CG",
        deityDomain: "Life",
        deitySymbol: "Triangle of three six-pointed stars",
      },
      {
        deityName: "Loviatar, goddess of pain",
        deityAlignment: "LE",
        deityDomain: "Death",
        deitySymbol: "Nine-tailed barbed scourge",
      },
      {
        deityName: "Malar, god of the hunt",
        deityAlignment: "CE",
        deityDomain: "Nature",
        deitySymbol: "Clawed paw",
      },
      {
        deityName: "Mask, god of thieves",
        deityAlignment: "CN",
        deityDomain: "Trickery",
        deitySymbol: "Black mask",
      },
      {
        deityName: "Mielikki, goddess of forests",
        deityAlignment: "NG",
        deityDomain: "Nature",
        deitySymbol: "Unicorn’s head",
      },
      {
        deityName: "Milil, god of poetry and song",
        deityAlignment: "NG",
        deityDomain: "Light",
        deitySymbol: "Five-stringed harp made of leaves",
      },
      {
        deityName: "Myrkul, god of death",
        deityAlignment: "NE",
        deityDomain: "Death",
        deitySymbol: "White human skull",
      },
      {
        deityName: "Mystra, goddess of magic",
        deityAlignment: "NG",
        deityDomain: "Knowledge",
        deitySymbol:
          "Circle of seven stars, or nine stars encircling a flowing red mist, or a single star",
      },
      {
        deityName: "Oghma, god of knowledge",
        deityAlignment: "N",
        deityDomain: "Knowledge",
        deitySymbol: "Black scroll",
      },
      {
        deityName: "Savras, god of divination and fate",
        deityAlignment: "LN",
        deityDomain: "Knowledge",
        deitySymbol: "Crystal ball containing many kinds of eyes",
      },
      {
        deityName: "Selûne, goddess of the moon",
        deityAlignment: "CG",
        deityDomain: "Knowledge, Life",
        deitySymbol: "Pair of eyes surrounded by seven stars",
      },
      {
        deityName: "Shar, goddess of darkness and loss",
        deityAlignment: "NE",
        deityDomain: "Death, Trickery",
        deitySymbol: "Black disk encircled with a border",
      },
      {
        deityName: "Silvanus, god of wild nature",
        deityAlignment: "N",
        deityDomain: "Nature",
        deitySymbol: "Oak leaf",
      },
      {
        deityName: "Sune, goddess of love and beauty",
        deityAlignment: "CG",
        deityDomain: "Life, Light",
        deitySymbol: "Face of a beautiful red-haired woman",
      },
      {
        deityName: "Talona, goddess of disease and poison",
        deityAlignment: "CE",
        deityDomain: "Death",
        deitySymbol: "Three teardrops on a triangle",
      },
      {
        deityName: "Talos, god of storms",
        deityAlignment: "CE",
        deityDomain: "Tempest",
        deitySymbol: "Three lightning bolts radiating from a central point",
      },
      {
        deityName: "Tempus, god of war",
        deityAlignment: "N",
        deityDomain: "War",
        deitySymbol: "Upright flaming sword",
      },
      {
        deityName: "Torm, god of courage and self-sacrifice",
        deityAlignment: "LG",
        deityDomain: "War",
        deitySymbol: "White right gauntlet",
      },
      {
        deityName: "Tymora, goddess of good fortune",
        deityAlignment: "CG",
        deityDomain: "Trickery",
        deitySymbol: "Face-up coin",
      },
      {
        deityName: "Tyr, god of justice",
        deityAlignment: "LG",
        deityDomain: "War",
        deitySymbol: "Balanced scales resting on a warhammer",
      },
      {
        deityName: "Umberlee, goddess of the sea",
        deityAlignment: "CE",
        deityDomain: "Tempest",
        deitySymbol: "Wave curling left and right",
      },
      {
        deityName: "Waukeen, goddess of trade",
        deityAlignment: "N",
        deityDomain: "Knowledge, Trickery",
        deitySymbol: "Upright coin with Waukeen’s profile facing left",
      },
    ],
  },
];
