export const Cantrips = [
  "None",
  "Acid Splash",
  "Chill Touch",
  "Dancing Lights",
  "Guidance",
  "Light",
  "Mage Hand",
  "Mending",
  "Message",
  "Minor Illusion",
  "Prestidigitation",
  "Produce Flame",
  "Ray of Frost",
  "Resistance",
  "Sacred Flame",
  "Shillelagh",
  "Shocking Grasp",
  "Thaumaturgy",
  "True Strike",
];

export const First = [
  "None",
  "Alarm",
  "Bane",
  "Bless",
  "Burning Hands",
  "Charm Person",
  "Color Spray",
  "Command",
  "Comprehend Languages",
  "Create or Destroy Water",
  "Create or Destroy Water",
  "Cure Wounds",
  "Detect Evil and Good",
  "Detect Magic",
  "Detect Magic",
  "Detect Poison and Disease",
  "Disguise Self",
  "Divine Favor",
  "Entangle",
  "Expeditious Retreat",
  "Faerie Fire",
  "False Life",
  "Feather Fall",
  "Floating Disk",
  "Fog Cloud",
  "Grease",
  "Guiding Bolt",
  "Healing Word",
  "Heroism",
  "Hideous Laughter",
  "Identify",
  "Illusory Script",
  "Inflict Wounds",
  "Jump",
  "Longstrider",
  "Mage Armor",
  "Magic Missile",
  "Protection from Evil and Good",
  "Purify Food and Drink",
  "Sanctuary",
  "Shied of Faith",
  "Shield of Faith",
  "Shield",
  "Silent Image",
  "Sleep",
  "Speak with Animals",
  "Thunderwave",
  "Unseen Servant",
];

export const Second = [
  "None",
  "Acid Arrow",
  "Aid",
  "Alter Self",
  "Animal Messenger",
  "Arcane Lock",
  "Arcanist’s Magic Aura",
  "Augury",
  "Barkskin",
  "Blindness/Deafness",
  "Blur",
  "Calm Emotions",
  "Continual Flame",
  "Darkness",
  "Darkvision",
  "Detect Thoughts",
  "Enhance Ability",
  "Enlarge/Reduce",
  "Enthrall",
  "Find Steed",
  "Find Traps",
  "Flame Blade",
  "Flaming Sphere",
  "Gentle Repose",
  "Gust of Wind",
  "Heat Metal",
  "Hold Person",
  "Invisibility",
  "Knock",
  "Lesser Restoration",
  "Levitate",
  "Locate Animals or Plants",
  "Locate Object",
  "Magic Mouth",
  "Magic Weapon",
  "Mirror Image",
  "Misty Step",
  "Moonbeam",
  "Pass without Trace",
  "Prayer of Healing",
  "Protection from Poison",
  "Ray of Enfeeblement",
  "Rope Trick",
  "Scorching Ray",
  "See Invisibility",
  "Shatter",
  "Silence",
  "Spider Climb",
  "Spike Growth",
  "Spiritual Weapon",
  "Suggestion",
  "Warding Bond",
  "Web",
  "Zone of Truth",
];

export const Third = [
  "None",
  "Animate Dead",
  "Beacon of Hope",
  "Bestow Curse",
  "Blink",
  "Call Lightning",
  "Clairvoyance",
  "Conjure Animals",
  "Create Food and Water",
  "Daylight",
  "Dispel Magic",
  "Fear",
  "Fireball",
  "Fly",
  "Gaseous Form",
  "Glyph of Warding",
  "Haste",
  "Hypnotic Pattern",
  "Lightning Bolt",
  "Magic Circle",
  "Major Image",
  "Mass Healing Word",
  "Meld into Stone",
  "Nondetection",
  "Phantom Steed",
  "Plant Growth",
  "Protection from Energy",
  "Remove Curse",
  "Revivify",
  "Sending",
  "Sleet Storm",
  "Slow",
  "Speak with Dead",
  "Speak with Plants",
  "Spirit Guardians",
  "Stinking Cloud",
  "Tiny Hut",
  "Tongues",
  "Vampiric Touch",
  "Water Breathing",
  "Water Walk",
  "Wind Wall",
];

export const Fourth = [
  "None",
  "Arcane Eye",
  "Banishment",
  "Black Tentacles",
  "Blight",
  "Confusion",
  "Conjure Minor Elementals",
  "Conjure Woodland Beings",
  "Control Water",
  "Death Ward",
  "Dimension Door",
  "Divination",
  "Dominate Beast",
  "Fabricate",
  "Faithful Hound",
  "Fire Shield",
  "Freedom of Movement",
  "Giant Insect",
  "Greater Invisibility",
  "Hallucinatory Terrain",
  "Ice Storm",
  "Locate Creature",
  "Phantasmal Killer",
  "Polymorph",
  "Private Sanctum",
  "Resilient",
  "Secret Chest",
  "Sphere",
  "Stone Shape",
  "Stoneskin",
  "Wall of Fire",
];

export const Fifth = [
  "None",
  "Animate Objects",
  "Antilife Shell",
  "Arcane Hand",
  "Awaken",
  "Cloudkill",
  "Commune with Nature",
  "Commune",
  "Cone of Cold",
  "Conjure Elemental",
  "Contact Other Plane",
  "Contagion",
  "Creation",
  "Dispel Evil and Good",
  "Dominate Person",
  "Dream",
  "Flame Strike",
  "Geas",
  "Greater Restoration",
  "Hallow",
  "Hold Monster",
  "Insect Plague",
  "Legend Lore",
  "Legend",
  "Lore",
  "Mass Cure Wounds",
  "Mislead",
  "Modify Memory",
  "Passwall",
  "Planar Binding",
  "Raise Dead",
  "Reincarnate",
  "Scrying",
  "Seeming",
  "Telekinesis",
  "Telepathic Bond",
  "Teleportation Circle",
  "Tree Stride",
  "Wall of Force",
  "Wall of Stone",
];

export const Sixth = [
  "None",
  "Blade Barrier",
  "Chain Lightning",
  "Circle of Death",
  "Conjure Fey",
  "Contingency",
  "Create Undead",
  "Disintegrate",
  "Eyebite",
  "Find the Path",
  "Flesh to Stone",
  "Forbiddance",
  "Freezing Sphere",
  "Globe of Invulnerability",
  "Guards and Wards",
  "Harm",
  "Heal",
  "Heroes’ Feast",
  "Instant Summons",
  "Irresistible Dance",
  "Magic Jar",
  "Mass Suggestion",
  "Move Earth",
  "Planar Ally",
  "Programmed Illusion",
  "Sunbeam",
  "Transport via Plants",
  "True Seeing",
  "Wall of Ice",
  "Wall of Thorns",
  "Wind Walk",
  "Word of Recall",
];

export const Seventh = [
  "None",
  "Arcane Sword",
  "Conjure Celestial",
  "Delayed Blast",
  "Divine Word",
  "Etherealness",
  "Finger of Death",
  "Fire Storm",
  "Fireball",
  "Forcecage",
  "Magnificent Mansion",
  "Mirage Arcane",
  "Plane Shift",
  "Prismatic Spray",
  "Project Image",
  "Regenerate",
  "Resurrection",
  "Reverse Gravity",
  "Sequester",
  "Simulacrum",
  "Symbol",
  "Teleport",
];

export const Eigth = [
  "None",
  "Antimagic Field",
  "Antipathy/Sympathy",
  "Clone",
  "Control Weather",
  "Demiplane",
  "Dominate Monster",
  "Earthquake",
  "Feeblemind",
  "Glibness",
  "Holy Aura",
  "Incendiary Cloud",
  "Maze",
  "Mind Blank",
  "Power Word Stun",
  "Power Word",
  "Stun",
  "Sunburst",
];

export const Nineth = [
  "None",
  "Astral Projection",
  "Foresight",
  "Gate",
  "Imprisonment",
  "Mass Heal",
  "Meteor Swarm",
  "Power Word Kill",
  "Prismatic Wall",
  "Shapechange",
  "Time Stop",
  "True Polymorph",
  "True Resurrection",
  "Weird",
  "Wish",
];
