export const STR = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];

export const DEX = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];

export const CON = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];

export const INT = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];

export const WIS = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];

export const CHA = [
    { value: "5", viewValue: "5 (-3)", suffix: "-3" },
    { value: "6", viewValue: "6 (-2)", suffix: "-2" },
    { value: "7", viewValue: "7 (-2)", suffix: "-2" },
    { value: "8", viewValue: "8 (-1)", suffix: "-1" },
    { value: "9", viewValue: "9 (-1)", suffix: "-1" },
    { value: "10", viewValue: "10 (+0)", suffix: "0" },
    { value: "11", viewValue: "11 (+0)", suffix: "0" },
    { value: "12", viewValue: "12 (+1)", suffix: "+1" },
    { value: "13", viewValue: "13 (+1)", suffix: "+1" },
    { value: "14", viewValue: "14 (+2)", suffix: "+2" },
    { value: "15", viewValue: "15 (+2)", suffix: "+2" },
    { value: "16", viewValue: "16 (+3)", suffix: "+3" },
    { value: "17", viewValue: "17 (+3)", suffix: "+3" },
    { value: "18", viewValue: "18 (+4)", suffix: "+4" },
    { value: "19", viewValue: "19 (+4)", suffix: "+4" },
    { value: "20", viewValue: "20 (+5)", suffix: "+5" },
    { value: "21", viewValue: "21 (+5)", suffix: "+5" },
    { value: "22", viewValue: "22 (+6)", suffix: "+6" },
    { value: "23", viewValue: "23 (+6)", suffix: "+6" },
    { value: "24", viewValue: "24 (+7)", suffix: "+7" },
    { value: "25", viewValue: "25 (+7)", suffix: "+7" },
    { value: "26", viewValue: "26 (+8)", suffix: "+8" },
    { value: "27", viewValue: "27 (+8)", suffix: "+8" },
    { value: "28", viewValue: "28 (+9)", suffix: "+9" },
];



