import { Classes } from "./classes";

export const SORCERER: Classes[] = [
  {
    value: 1,
    viewValue: "1st",
    sorceryPoints: 0,
    spellsKnown: 2,
    cantrips: 4,
    first: 2,
    second: null,
    third: null,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 2,
    viewValue: "2nd",
    sorceryPoints: 2,
    spellsKnown: 3,
    cantrips: 4,
    first: 3,
    second: null,
    third: null,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 3,
    viewValue: "3rd",
    sorceryPoints: 3,
    spellsKnown: 4,
    cantrips: 3,
    first: 4,
    second: 2,
    third: null,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 4,
    viewValue: "4th",
    sorceryPoints: 4,
    spellsKnown: 5,
    cantrips: 5,
    first: 4,
    second: 3,
    third: null,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 5,
    viewValue: "5th",
    sorceryPoints: 5,
    spellsKnown: 6,
    cantrips: 5,
    first: 4,
    second: 3,
    third: 2,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 6,
    viewValue: "6th",
    sorceryPoints: 6,
    spellsKnown: 7,
    cantrips: 5,
    first: 4,
    second: 3,
    third: 3,
    fourth: null,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 7,
    viewValue: "7th",
    sorceryPoints: 7,
    spellsKnown: 8,
    cantrips: 5,
    first: 4,
    second: 3,
    third: 3,
    fourth: 1,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 8,
    viewValue: "8th",
    sorceryPoints: 8,
    spellsKnown: 9,
    cantrips: 5,
    first: 4,
    second: 3,
    third: 3,
    fourth: 2,
    fifth: null,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 9,
    viewValue: "9th",
    sorceryPoints: 9,
    spellsKnown: 10,
    cantrips: 5,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 1,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 10,
    viewValue: "10th",
    sorceryPoints: 10,
    spellsKnown: 11,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: null,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 11,
    viewValue: "11th",
    sorceryPoints: 11,
    spellsKnown: 12,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 12,
    viewValue: "12th",
    sorceryPoints: 12,
    spellsKnown: 12,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: null,
    eigth: null,
    nineth: null
  },
  {
    value: 13,
    viewValue: "13th",
    sorceryPoints: 13,
    spellsKnown: 13,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: 1,
    eigth: null,
    nineth: null
  },
  {
    value: 14,
    viewValue: "14th",
    sorceryPoints: 14,
    spellsKnown: 13,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: 1,
    eigth: null,
    nineth: null
  },
  {
    value: 15,
    viewValue: "15th",
    sorceryPoints: 15,
    spellsKnown: 14,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: 1,
    eigth: 1,
    nineth: null
  },
  {
    value: 16,
    viewValue: "16th",
    sorceryPoints: 16,
    spellsKnown: 14,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: 1,
    eigth: 1,
    nineth: null
  },
  {
    value: 17,
    viewValue: "17th",
    sorceryPoints: 17,
    spellsKnown: 15,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 2,
    sixth: 1,
    seventh: 1,
    eigth: 1,
    nineth: 1
  },
  {
    value: 18,
    viewValue: "18th",
    sorceryPoints: 18,
    spellsKnown: 15,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 3,
    sixth: 1,
    seventh: 1,
    eigth: 1,
    nineth: 1
  },
  {
    value: 19,
    viewValue: "19th",
    sorceryPoints: 19,
    spellsKnown: 15,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 3,
    sixth: 2,
    seventh: 1,
    eigth: 1,
    nineth: 1
  },
  {
    value: 20,
    viewValue: "20th",
    sorceryPoints: 20,
    spellsKnown: 15,
    cantrips: 6,
    first: 4,
    second: 3,
    third: 3,
    fourth: 3,
    fifth: 3,
    sixth: 2,
    seventh: 2,
    eigth: 1,
    nineth: 1
  }
];
